# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 212cc375aacf57085a5832aff6be7484c6b44bc815376208099c30b3b130be6465beeeae499551ce6c05e0c52ab9db1401a8612c9bc413fe7fa850dac326313d

test:
  secret_key_base: 3e542304dd124c80164932fb641dfdb184217173c15ded9a3b9205a0bf1fc968ae8dc111dbd19c4168ab52d7f6250df015fdc3d0203161445ef46647dc1c4b70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
